* arvidsson.io
[[https://github.com/chip2n/arvidsson.io/workflows/deploy/badge.svg]]

My personal website!

This website is generated using some custom code written in Common Lisp. I've
only tested it on Linux using SBCL.

** Build the website

Build the website using Nix:

#+begin_src bash
nix run
#+end_src

The files are placed in ~./public/~.

** Starting the development server

The development server compiles the pages and serves the files locally using
hunchentoot. The page is reloaded through websocket connections when a static
file is modified, or when a tag/page definition is recompiled in the lisp image.

You'll first need to manually pull down the artifacts for all projects that
aren't being built by Nix yet:

#+begin_src bash
./fetch-deps.sh
#+end_src

Then, enter the Nix dev shell:

#+begin_src bash
nix develop
#+end_src

Finally, launch ~sbcl~, load the ~site~ system and run:

#+begin_src lisp
(site:start-dev)
#+end_src

When starting the development server, a separate system ~site/live~  is loaded
which uses some extra dependencies (for watching files, serving HTTP etc).
